import QueryProvider from "@/libs/react-query/QueryProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastifyComponent from "@/libs/react-toastify/ToastifyComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          {children}
          <ToastifyComponent/>
        </QueryProvider>
      </body>
    </html>
  );
}
